### ISSUE TITLE
Wrong output handling when the output contains "'" (single quote)

### ISSUE THREAD

**Issue by cinsk** [pope/ob-go#1]
```
    #+BEGIN_SRC go :imports "fmt"
    s := "'h' and 'i'"
    fmt.Printf("%s\n", s)
    #+END_SRC

    #+RESULTS:
    : h
```

When I evaluate a Go snippet looks like above, the output was not properly shown.

**Comment by pope** [comment]
Thanks for the report. Let's see if I can get to the bottom of this.

**Comment by zakame** [comment]
``` go
#+BEGIN_SRC go :imports "fmt" :results output table
s := "'h' and 'i'"
fmt.Printf("%s\n", s)
#+END_SRC

#+RESULTS:
: 'h' and 'i'
```

I think the check for table/vector result in `org-babel-execute:go` needs work.  I assumed the default `:results output` also implied `verbatim` so that there's no extra output processing, so maybe explicitly default to that instead?
