### ISSUE TITLE
an error happen "cannot run non-main package"

### ISSUE THREAD

**Issue by sillygod** [pope/ob-go#14]
hi, I recently found this package and try it with a code snippet and something wrong happens.

here is the screenshot. ![img](http://i.imgur.com/6eMp8iG.png)

**Comment by robrohan** [comment]
Emacs 26.1; golang 1.12.6; ob-go installed from melpa - with a simplified version of what you did it seems to work.  I am not going to type your full code from your picture, is there possibly a bug with the go code itself?

![Screen Shot 2019-10-11 at 7 59 00 PM](https://user-images.githubusercontent.com/29180/66631020-e0dbe100-ec61-11e9-9412-e6f1ad8fbe4d.png)

**Comment by sillygod** [comment]
@robrohan I have not used this package for a long time and today I try it again. It works! However, I don't know why it failed before.
