### ISSUE TITLE
Support the ability for :package to be set to none

### ISSUE THREAD

**Issue by antonhibl** [pope/ob-go#30]
I am trying to tangle an org file consisting of go code blocks which are all tangled into one file. This package works pretty well besides the inability to set :package to none. For instance, when I untangle I set it so that :main no is a default argument for source blocks but there is no ability to set :package to an empty string or nil leading to the resulting tangled file being filled with various 'package main' lines all over for each source block. Adding this would definitely be useful for overall literate go programming with the package.

**Comment by antonhibl** [comment]
for future readers, this is actually possible by setting :package to 'discard, i.e. `:package 'discard`

**Comment by pope** [comment]
Thanks. and thanks for the note!

**Comment by antonhibl** [comment]
@pope opened a PR (#31) for a doc change with this note about :package, its a small one line change but I think people will appreciate it.
