### ISSUE TITLE
error with package 

### ISSUE THREAD

**Issue by micanzhang** [pope/ob-go#8]
when i wrote org like this:
# +BEGIN_SRC go

package main

import "fmt"

func main() {
    fmt.Println("Hello World!")
}
# +END_SRC

and execute this code, i got:

```
package main: 
/var/folders/m0/l7hfbwvn3dz9qnx_dxf65vvm0000gp/T/babel-31761XsV/go-src-31761BqN.go:2:1: expected 'package', found 'import'
```

so, i check out generated go source hinted by above, and i found:

```

import (

)


package main
import "fmt"

func main() {
    fmt.Println("Hello World!")
}%
```

is it a bug or my problem?

**Comment by pope** [comment]
This is a bug. https://github.com/pope/ob-go/blob/master/ob-go.el#L178 should exit early if there aren't any inputs.

The normal use case would be

```
#+BEGIN_SRC go :imports "fmt"
fmt.Println("Hello, World!")
#+END_SRC
```

Less about adding in "real" Go source. But I think we should be able to accommodate this. If you have time, I'm accepting patches with a simple test showing it works :D

**Comment by micanzhang** [comment]
related pr: https://github.com/pope/ob-go/pull/13
